argocd:
  namespace: openshift-gitops
gitops:
  repoURL: https://github.com/sabre1041/ansible-devspaces-fsc.git
  targetRevision: main

openshiftPipelines:
  name: openshift-pipelines
  namespace: openshift-pipelines

devspaces:
  name: devspaces
  namespace: openshift-devspaces

openvsx:
  name: openvsx
  namespace: che-openvsx

workspaceImages:
  name: workspace-images
  namespace: workspace-images
