apiVersion: v1
kind: Secret
metadata:
  name: open-vsx-pg
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: env
    {{- include "devspaces-instance.argocd-syncwave" . | nindent 4 }}
type: Opaque
data:
  LLM_API_KEY: "{{ printf "{{ .api_key }}" }}"
  LLM_BASE_URL: "{{ printf "{{ .base_url }}" }}"

  
